const SantriData = [
  {
    id_1: 141,
    hp: 85315012716,
    job: "Kerja",
    mou: "santri",
    name: "Saeful Anwar",
    stay: "Iya",
    email: "saefulanwar1417@gmail.com",
    branch: null,
    id: 1,
    name2: "Pondok Programmer, Kretek",
    gender: "Laki-laki",
    address:
      "Jalan Mayor Dedeng Sukanta No.23 RT/RW 21/07 Kelurahan Pasirkareumbi Subang",
    province: "Jawa Barat",
    id_santri: "20525IG1129HS",
    birth_date: "1996-09-09",
    generation: 9,
    department_end_id: 7,
    prodi_id: 6,
    status_id: 2,
    aktif_y_n_id: 2,
  },
  {
    id_1: 43,
    hp: 82324320797,
    job: "Kerja",
    mou: "alumni",
    name: "Pujiningsih",
    stay: "Tidak",
    email: "asahinamikuru4@gmail.com",
    branch: null,
    id: 1,
    name2: "Kantor Manajemen Akhwat",
    gender: "Perempuan",
    address:
      "Ds. Karangsari Dk. Mlaten II RT.03 RW.04 Kec. Karanganyar Kab. Pekalongan Jawa Tengah 51182",
    province: "Jawa Tengah",
    id_santri: "18743GU143HU",
    birth_date: "2000-06-02",
    generation: null,
    department_end_id: 6,
    prodi_id: null,
    status_id: 2,
    aktif_y_n_id: 2,
  },
  {
    id_1: 55,
    hp: 85729643706,
    job: "Kerja",
    mou: "alumni",
    name: "Intan Habibatul Latifah",
    stay: "Tidak",
    email: "intanhl@gmail.com",
    branch: null,
    id: 1,
    name2: "Kantor Manajemen Akhwat",
    gender: "Perempuan",
    address: "Petir, Srimartani, Piyungan, Bantul, Yogyakarta",
    province: "Sumatera Barat",
    id_santri: "19745NM455PJ",
    birth_date: "2002-09-24",
    generation: null,
    department_end_id: 7,
    prodi_id: null,
    status_id: 2,
    aktif_y_n_id: 2,
  },
  {
    id_1: 60,
    hp: 85526262524,
    job: "Kerja",
    mou: "alumni",
    name: "Praditya Soluna Puspita",
    stay: "Tidak",
    email: "praditya.soluna@gmail.com",
    branch: null,
    id: 1,
    name2: "Pondok Marketer, Kalakijo",
    gender: "Perempuan",
    address: "JL,BOGOWONTO RT05/05 NO 67,DONAN CILACAP TENGAH",
    province: "Jawa Tengah",
    id_santri: "23545GS00750PI",
    birth_date: "2000-10-12",
    generation: null,
    department_end_id: 4,
    prodi_id: null,
    status_id: 2,
    aktif_y_n_id: 2,
  },
  {
    id_1: 74,
    hp: 82237178331,
    job: "Kerja",
    mou: "santri",
    name: "Aufa Syamsiah",
    stay: "Tidak",
    email: "arifgsim@gmail.coma",
    branch: null,
    id: 1,
    name2: "Kantor Manajemen Akhwat",
    gender: "Perempuan",
    address: "Jl. Ma'unori, Kec. Keo Tengah, Kab. Nagekeo",
    province: "Sumatera Selatan",
    id_santri: "20118OP1577DT",
    birth_date: "2002-02-18",
    generation: null,
    department_end_id: 6,
    prodi_id: null,
    status_id: 2,
    aktif_y_n_id: 2,
  },
  {
    id_1: 76,
    hp: 8998716651,
    job: "Kerja",
    mou: "santri",
    name: "Salma Hanifah",
    stay: "Iya",
    email: "saufafastq@gmail.com",
    branch: null,
    id: 1,
    name2: "Pondok Marketer, Kalakijo",
    gender: "Perempuan",
    address: "Puluhdadi 397-B Seturan, Caturtunggal Depok Sleman",
    province: "Jawa Tengah",
    id_santri: "23253BR00750LG",
    birth_date: "2000-12-24",
    generation: 9,
    department_end_id: 7,
    prodi_id: 6,
    status_id: 2,
    aktif_y_n_id: 2,
  },
  {
    id_1: 392,
    hp: 81327637886,
    job: "Kerja",
    mou: "santri",
    name: "Fatah Zaki Al Barik",
    stay: "Tidak",
    email: "fazakrialbarik@gmail.com",
    branch: null,
    id: 1,
    name2: "Pesantren IT Tamanan 2",
    gender: "Laki-laki",
    address: "Kalipakis RT05 Tirtonirmolo kasihan bantul DI Yogyakarta",
    province: "Yogyakarta",
    id_santri: "21703FC2488AZ",
    birth_date: "2002-04-19",
    generation: 13,
    department_end_id: 5,
    prodi_id: 3,
    status_id: 1,
    aktif_y_n_id: 2,
  },
  {
    id_1: 395,
    hp: 83195234446,
    job: "Kerja",
    mou: "santri",
    name: "Indra Damar Jati",
    stay: "Tidak",
    email: "indradamarjati21@gmail.com",
    branch: null,
    id: 1,
    name2: "Pesantren IT Tamanan 2",
    gender: "Laki-laki",
    address: "Jalan Sampar Angin No.18 RT1 RW1, Teluk, Purwokerto Selatan.",
    province: "Jawa Tengah",
    id_santri: "21133YT2226XK",
    birth_date: "2002-08-21",
    generation: 13,
    department_end_id: 5,
    prodi_id: 4,
    status_id: 1,
    aktif_y_n_id: 2,
  },
  {
    id_1: 430,
    hp: 81312233554,
    job: "Kerja",
    mou: "santri",
    name: "Muhmmad Yusuf Suryakusuma",
    stay: "Iya",
    email: "muhammadyusufsonne@gmail.com",
    branch: null,
    id: 1,
    name2: "Pondok Programmer, Kretek",
    gender: "Laki-laki",
    address:
      "Perum Griya Sakinah Permai Jln. Raya Mangu Km. 04 No 2 Dsn Grenjeng RT 07/01 Kenteng Nogosari Boyolali 57378",
    province: "Jakarta",
    id_santri: "23925KZ00750NR",
    birth_date: "2001-06-01",
    generation: 13,
    department_end_id: 6,
    prodi_id: 6,
    status_id: 2,
    aktif_y_n_id: 2,
  },
  {
    id_1: 183,
    hp: 85695078232,
    job: "Project External",
    mou: "santri",
    name: "Jujun Setiawan",
    stay: "Iya",
    email: "jujunsetiawan10@gmail.com",
    branch: null,
    id: 1,
    name2: "Pondok Programmer, Kretek",
    gender: "Laki-laki",
    address: "Jl.Swantantra 1, Gg.TMMD 1, Rt.04 Rw.05 Jatiasih kota Bekasi",
    province: "Jawa Barat",
    id_santri: "23109OU00751OG",
    birth_date: "2001-10-09",
    generation: 9,
    department_end_id: 5,
    prodi_id: 4,
    status_id: 2,
    aktif_y_n_id: 2,
  },
  {
    id_1: 185,
    hp: 88218720383,
    job: "Project External",
    mou: "santri",
    name: "Muhammad Radiant Fadilah",
    stay: "Iya",
    email: "radiantfadilah0@gmail.com",
    branch: null,
    id: 1,
    name2: "Pondok Programmer, Kretek",
    gender: "Laki-laki",
    address:
      "Jawa Barat, Bandung, Kec. Cangkuang, Desa Pananjung, Bumi Parahyangan Kencana, Blok G 21, No.23",
    province: "Kalimantan Timur",
    id_santri: "23429WD00750KR",
    birth_date: "2002-08-11",
    generation: 9,
    department_end_id: 5,
    prodi_id: 4,
    status_id: 2,
    aktif_y_n_id: 2,
  },
  {
    id_1: 188,
    hp: 8996670703,
    job: "Kerja",
    mou: "santri",
    name: "Muhammad Yahya Suhada",
    stay: "Iya",
    email: "syuhadayahya9@gmail.com",
    branch: null,
    id: 1,
    name2: "Pondok Programmer, Kretek",
    gender: "Laki-laki",
    address:
      "Jln. Karya bakti, Gg. Jerah, Rt 01/06, No. 20A, Kel. Tanah baru, Kec. Beji, Depok, Jawa barat",
    province: "Kalimantan Timur",
    id_santri: "23436XK00751XD",
    birth_date: "2000-09-07",
    generation: 9,
    department_end_id: 5,
    prodi_id: 4,
    status_id: 2,
    aktif_y_n_id: 2,
  },
  {
    id_1: 236,
    hp: null,
    job: "Project External",
    mou: "santri",
    name: "Muhammad David Ismail Ms",
    stay: "Iya",
    email: null,
    branch: null,
    id: 1,
    name2: "Pondok Programmer, Kretek",
    gender: "Laki-laki",
    address: null,
    province: "Kalimantan Timur",
    id_santri: "23929RO00750BG",
    birth_date: "1970-01-01",
    generation: 9,
    department_end_id: 5,
    prodi_id: 3,
    status_id: 2,
    aktif_y_n_id: 2,
  },
  {
    id_1: 269,
    hp: 82285518052,
    job: "Kerja",
    mou: "santri",
    name: "Eva Suryaningti Yas",
    stay: "Tidak",
    email: "evasuryanngtyas81@gmail.om",
    branch: null,
    id: 1,
    name2: "Kantor Manajemen Akhwat",
    gender: "Perempuan",
    address:
      "Sitiung 3 Blok C Jorong Batas Baru, Kec Sungai Rumbai, Kab Dharmasraya",
    province: "Sumatera Barat",
    id_santri: "20216MR1912ZI",
    birth_date: "2001-01-20",
    generation: null,
    department_end_id: 6,
    prodi_id: null,
    status_id: 2,
    aktif_y_n_id: 2,
  },
  {
    id_1: 274,
    hp: 85733761604,
    job: "Kerja",
    mou: "santri",
    name: "Shinta Juliana Putri",
    stay: "Iya",
    email: "febyalailitri@gmail.com",
    branch: null,
    id: 1,
    name2: "Kantor Manajemen Akhwat",
    gender: "Perempuan",
    address: "Ds.Tulung Rt 07 Rw 03 Kec. Kedamean Kab. Gresik",
    province: "Jawa Timur",
    id_santri: "23753WA00751MK",
    birth_date: "2001-07-01",
    generation: null,
    department_end_id: 7,
    prodi_id: null,
    status_id: 2,
    aktif_y_n_id: 2,
  },
  {
    id_1: 341,
    hp: 85753084596,
    job: "Kerja",
    mou: "santri",
    name: "Muhammad Amin",
    stay: "Tidak",
    email: "nilwanwijaya93@gmail.com",
    branch: null,
    id: 1,
    name2: "Pondok Programmer, Kretek",
    gender: "Laki-laki",
    address:
      "jalan raya parit lintang rt21 rw08 desa kalimas kecamatan sunggai kakap kabupaten kubu raya provinsi kalimantan barat",
    province: "Kalimantan Barat",
    id_santri: "21924GH2321VL",
    birth_date: "2000-01-02",
    generation: 14,
    department_end_id: 6,
    prodi_id: 8,
    status_id: 2,
    aktif_y_n_id: 2,
  },
  {
    id_1: 346,
    hp: 81293122365,
    job: "Kerja",
    mou: "santri",
    name: "Mazaya Jazmina",
    stay: "Tidak",
    email: "mazayzmj@gmail.com",
    branch: null,
    id: 1,
    name2: "Kantor Manajemen Akhwat",
    gender: "Perempuan",
    address:
      "Permata Legenda 2 blok PA10/5 Kel. Mustika Jaya, Kec. Mustika Jaya, Bekasi, Jawa Barat.",
    province: "Jawa Barat",
    id_santri: "21137DT2460PS",
    birth_date: "2003-07-14",
    generation: 14,
    department_end_id: 7,
    prodi_id: 7,
    status_id: 2,
    aktif_y_n_id: 2,
  },
  {
    id_1: 368,
    hp: 89626394794,
    job: "Kerja",
    mou: "santri",
    name: "Khanif Roziqin",
    stay: "Iya",
    email: "roziqinkhanif@gmail.com",
    branch: null,
    id: 1,
    name2: "Pondok Programmer, Kretek",
    gender: "Laki-laki",
    address: "Semawungan RT 06 RW 03 Gondowanngi sawangan Magelang",
    province: "Jawa Tengah",
    id_santri: "21156JB2123ZX",
    birth_date: "2001-09-02",
    generation: 13,
    department_end_id: 7,
    prodi_id: 7,
    status_id: 2,
    aktif_y_n_id: 2,
  },
  {
    id_1: 387,
    hp: 82311683426,
    job: "Kerja",
    mou: "santri",
    name: "Erwin Sanjaya",
    stay: "Iya",
    email: "erwinsanjaya131002@gmail.com",
    branch: null,
    id: 1,
    name2: "Pondok Programmer, Kretek",
    gender: "Laki-laki",
    address:
      "Jl.mappasessu RT1 rw2,desa sungai jambat,kecamatan Sadu, kabupaten Tanjung Jabung timur, provinsi Jambi.",
    province: "Jambi",
    id_santri: "23765NU00751FA",
    birth_date: "2002-10-13",
    generation: 13,
    department_end_id: 5,
    prodi_id: 4,
    status_id: 2,
    aktif_y_n_id: 2,
  },
  {
    id_1: 574,
    hp: 81225349151,
    job: "Belum Kerja",
    mou: "santri",
    name: "Bayu Andrean",
    stay: "Iya",
    email: "Bayuandrean888@gmali.com",
    branch: null,
    id: 1,
    name2: "Pondok Programmer, Kretek",
    gender: "Laki-laki",
    address: "Dusun 4,desa Tanjung Telang, Prabumulih Barat, Prabumulih",
    province: "Sumatera Selatan",
    id_santri: "23525YV00751WH",
    birth_date: "2001-01-09",
    generation: 16,
    department_end_id: 4,
    prodi_id: 5,
    status_id: 1,
    aktif_y_n_id: 2,
  },
  {
    id_1: 575,
    hp: 81235664451,
    job: "Khidmat",
    mou: "santri",
    name: "FIKRI DZAKI SYUKRIANSYAH",
    stay: "Iya",
    email: "fdzaki72@gmail.com",
    branch: null,
    id: 1,
    name2: "Pondok Programmer, Kretek",
    gender: "Laki-laki",
    address:
      "DUSUN PLALANGAN RT 2 RW 2 DESA SUKAMAKMUR KECAMATAN AJUNG KABUPATEN JEMBER",
    province: "Jawa Timur",
    id_santri: "23963GG00751BA",
    birth_date: "2004-03-27",
    generation: 16,
    department_end_id: 4,
    prodi_id: 2,
    status_id: 2,
    aktif_y_n_id: 2,
  },
  {
    id_1: 576,
    hp: 8889971129,
    job: "Belum Kerja",
    mou: "santri",
    name: "Gian Laksana Prayoga",
    stay: "Iya",
    email: "gianlaksana1@gmail.com",
    branch: null,
    id: 1,
    name2: "Pondok Programmer, Kretek",
    gender: "Laki-laki",
    address:
      "Jl Samping pembensin Desa, Karangbale, Kec.Larangan,Kab.BREBES, JAWA TENGAH",
    province: "Jawa Tengah",
    id_santri: "23336OR00750WC",
    birth_date: "2004-01-16",
    generation: 16,
    department_end_id: 4,
    prodi_id: 2,
    status_id: 1,
    aktif_y_n_id: 2,
  },
  {
    id_1: 578,
    hp: 81289465851,
    job: "Khidmat",
    mou: "santri",
    name: "Muhammad Arifudin",
    stay: "Iya",
    email: "03arifudin@gmail.com",
    branch: null,
    id: 1,
    name2: "Pondok Programmer, Kretek",
    gender: "Laki-laki",
    address: "Jl. Karebet, RT. 24, RW 06, Desa Bogem, Kec. Gurah, Kab. Kediri",
    province: "Jawa Timur",
    id_santri: "23822HO00751XU",
    birth_date: "2002-07-21",
    generation: 16,
    department_end_id: 5,
    prodi_id: 3,
    status_id: 1,
    aktif_y_n_id: 2,
  },
  {
    id_1: 579,
    hp: 83890138213,
    job: "Magang",
    mou: "santri",
    name: "Muhammad Fauzan",
    stay: "Iya",
    email: "fauzan04062003@gmail.com",
    branch: null,
    id: 1,
    name2: "Pondok Programmer, Kretek",
    gender: "Laki-laki",
    address: "Des. Pasir angin kec. Cileungsi kab. Bogor",
    province: "Jawa Barat",
    id_santri: "23930BK00750HA",
    birth_date: "2003-06-04",
    generation: 16,
    department_end_id: 4,
    prodi_id: 2,
    status_id: 1,
    aktif_y_n_id: 2,
  },
  {
    id_1: 580,
    hp: 88224644323,
    job: "Khidmat",
    mou: "santri",
    name: "Muhammad Ibnu Muhammad Al Anam Al atsari",
    stay: "Iya",
    email: "muhammadibnumuhammad20051003@gmail.com",
    branch: null,
    id: 1,
    name2: "Pondok Programmer, Kretek",
    gender: "Laki-laki",
    address:
      "PERUM NILA ALAM PERMAI BLOK C22, RT 26 RW 3,KELURAHAN CIPEUCANG, KEC. CILEUNGSI,KAB. BOGOR, JAWA BARAT",
    province: "Jawa Barat",
    id_santri: "22426YV3382NY",
    birth_date: "2005-03-10",
    generation: 16,
    department_end_id: 4,
    prodi_id: 2,
    status_id: 2,
    aktif_y_n_id: 2,
  },
];

export default SantriData;
